# Lechuza board configuration

# Copyright (c) 2022 elagil
# SPDX-License-Identifier: MIT

identifier: lechuza
name: Lechuza
type: keyboard
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - switches
